### ISSUE TITLE
The discontinued product "redirect to category" functionality not working version 1.5

### ISSUE THREAD

**Issue by sinanispir** [adampmoss/CreareSEO#101]
If I disable an product and set redirect to category then the URL of this product is redirecting to the 404 page in case of the category. On the older versions it is working. In version 1.5 it is not working.

How can I fix this?

**Comment by hewgim** [comment]
We have the same problem since upgrading to 1.5 and have ended up with crawl errors in Google Webmaster Tools. Anyone know when/if this will be fixed.

Regards

Mark

**Comment by willcodeforfood** [comment]
Out of curiosity, do you have flat tables enabled for categories (or products, if you're having the same issue with discontinued products?)

**Comment by hewgim** [comment]
Hi @willcodeforfood,

The issue for us was a bug in app/code/community/Creare/CreareSeoCore/Helper/Data.php

The method

public function getDiscontinuedProductUrl($product)

has the line

$cats = $product->getCategoryIds();

to retrieve a list of category ids for the discontinued product.

Unfortunately we are running Magento with multiple websites and $product->getCategoryIds was returning category ids for ALL websites and store views. Ultimately the code was trying to redirect to a category on a different website !! 

I don't know if this helps your situation.

Regards

Mark

**Comment by willcodeforfood** [comment]
In our case, this feature was failing to work whenever flat tables are enabled. This appears to have broken in commit [Major refactoring of observer methods](https://github.com/adampmoss/CreareSEO/commit/3883b0088fa90025d53cf14a10ebffe3d25a531f) when a call to `...Product::load($id)` was replaced with a single-row return from a collection. The collection always uses flat tables if they are enabled, and the `creareseo_discontinued` is not marked for use in the flat tables, so it will never be a true-y value.

I hope to fix this and submit a pull request whenever I have time.
