### ISSUE TITLE
Apply NOINDEX To Parameter Pages

### ISSUE THREAD

**Issue by sprankhub** [adampmoss/CreareSEO#110]
There is already an option to apply NOINDEX to filtered category pages. It is checked whether the category is filtered with a check for a URL query / parameter:

    parse_url($action->getRequest()->getRequestUri(), PHP_URL_QUERY)

I suggest to add a new option e.g. `noindexparameterpages`, which applies NOINDEX to EVERY page, which contains such URL queries / parameters.

The idea comes from a SEO agency. If you do not apply a NOINDEX to such pages, a competitor may be able to fuck up your search results by pushing pages like `https://www.shop.de/some-product-or-page?cheaper=competitor-name`.

Do you agree @adampmoss? If this is the case, I am happy to provide a PR for this feature.

**Comment by adampmoss** [comment]
@sprankhub I'm not sure I follow 100% what the problem is, but happy for you to make a PR for me to review (I'll probably get it then!)
