### ISSUE TITLE
Enable Canonical Product Redirecting = "Yes" causing URL parameters not work

### ISSUE THREAD

**Issue by liketohelp** [adampmoss/CreareSEO#113]
Hi.

I am an analyst developer for my client's website [https://www.graceandgloryhome.co.uk/]

We have debugged and discovered that your Magento extension [CreareSEO version 1.4.] is not allowing query string parameters to be added to URLs.

i.e. we want to extend URLs as follows:

With = https://www.graceandgloryhome.co.uk/old-doctors-door-knocker.html?tmty=b&tmcv=0&utm_medium=email&utm_source=fr&tmcs=2bt0i94

Without = https://www.graceandgloryhome.co.uk/old-doctors-door-knocker.html

but when your extension has [Enable Canonical Product Redirecting = Yes] it is causing [With] to not load the page. Setting it to "No" is allowing [With] to be loaded.

Any ideas why this is breaking it please?

I'd like to understand the impact of setting Enable Canonical Product Redirecting = No, are you able to advise please?

Do you think we should upgrade version 1.5 of the extension and try again?

Many thanks in advance for your help.

Anil 
anil@liketohelp.com
07984325579

**Comment by liketohelp** [comment]
Hi Adam,

Sorry to bother you but please can you advise on this problem in particular what the impact of setting [Enable Canonical Product Redirecting = No] is as we are waiting for the answer to determine our next move regarding another integration which is currently not working due to this setting currently being Yes.

**Comment by cfgalvani** [comment]
I have the same problem here.

**Comment by sprankhub** [comment]
This issue has already been fixed with https://github.com/adampmoss/CreareSEO/commit/118482540b276460a0f6d42de217f116c7dfd3e2. @liketohelp please update to the latest version and you should be good.
