### ISSUE TITLE
Implement Image XML Sitemap

### ISSUE THREAD

**Issue by sprankhub** [adampmoss/CreareSEO#117]
It would be cool if this extension would support the creation of an image XML sitemap. I guess it is a good idea to create a separate sitemap for this. Do you agree? Would you merge a PR, which adds this functionality? Or do you think this should be a separate extension?

**Comment by sprankhub** [comment]
@adampmoss sorry that I bug you again. I really try to help as much as I can and try to bug you as few as possible. Could you just give me a short feedback? Either "cool idea, let us add it to CreareSeoCore" or "I do not want to have it in CreareSeoCore, please develop your own extension under your own namespace". Thanks!

**Comment by adampmoss** [comment]
@sprankhub I've never really read much into image sitemaps but it sounds relevant for the extension so happy to have it as part of the module. Go for it.

**Comment by sprankhub** [comment]
Fixed with https://github.com/adampmoss/CreareSEO/commit/210dd3743056e4967717e9deaa8aa671a7a8a479

**Comment by vishy93** [comment]
@sprankhub I have just updated to 1.5 and see the image sitemap incorporated, but sadly nowhere can I see how to generate one. Where would this option be?

**Comment by sprankhub** [comment]
@vishy93 it is automatically (re-)generated each night.

**Comment by vishy93** [comment]
@sprankhub Thanks for confirming Simon

**Comment by vishy93** [comment]
@sprankhub Sadly, nothing has been generated each night the folder is empty and looking in exception log I see a system cron error log.
