### ISSUE TITLE
ERR in system.log

### ISSUE THREAD

**Issue by bakkee** [adampmoss/CreareSEO#118]
Got a massage in system.log

ERR (3): Notice: Undefined variable: data  in /includes/src/Creare_CreareSeoCore_Helper_Meta.php on line 123

something you can fix?

**Comment by sprankhub** [comment]
Thanks for the report! Fixed with https://github.com/adampmoss/CreareSEO/commit/78723b12c70f500237c8e4bde2502717a74cb2ba.
