### ISSUE TITLE
Turpentine Varnish

### ISSUE THREAD

**Issue by cfgalvani** [adampmoss/CreareSEO#121]
I have just installed Turpentine Varnish and than I couldn't access my frontend product pages anymore. I got the error message "Too many redirections". The problem is that when I disabled the CreareSEO extension, the product pages start working. Does anybody know anything about it? Thank you!

**Comment by sprankhub** [comment]
Sounds weird to me since Creare SEO and Turpentine/Varnish have nothing in common. Which redirections are executed? You can check with the developer toolbar or a service like https://httpstatus.io/. Please post a screenshot of your Creare SEO settings.

**Comment by cfgalvani** [comment]
@sprankhub, obrigado pela rápida resposta. A URL a qual me refiro é essa: https://www.personalpapers.com.br/estojo-box-lego-rosa.html
Coloquei no https://httpstatus.io como solicitou e até agora nada. Estou tirando umas prints das config e já subo aqui

**Comment by cfgalvani** [comment]
![captura de tela 2017-08-17 as 03 41 46](https://user-images.githubusercontent.com/12137704/29399063-16cdd086-82fe-11e7-826c-7d36a6b76533.png)
Não estou usando Twitter Cards
Performance Cleanup tudo ativado
Default Page Title com tudo configurado
Standard Analytics
Com Organization Schema
Enabled Product Schema
Enabled Social Schema
Enabled Logo Schema
Enabled Breadcrumbs Schema
Google Tag -> Não
Google Content -> Não
Sitelinks Sim

**Comment by sprankhub** [comment]
Please edit your posts and translate them into English.

**Comment by cfgalvani** [comment]
@sprankhub sorry about it. =/

**Comment by sprankhub** [comment]
We need to know all redirects, which are executed. Please open the developer toolbar and check the redirects.

**Comment by cfgalvani** [comment]
Now the admin is with this same error. All redirects is to the same page.
Location: https://www.personalpapers.com.br/admin

![captura de tela 2017-08-17 as 04 05 55](https://user-images.githubusercontent.com/12137704/29399910-7493fea4-8301-11e7-9911-d6652af4ed11.png)

**Comment by cfgalvani** [comment]
The problem isn't with CreareSEO. I have just found this:
"Cannonical domain name redirects not working with Normalize Hosts enabled"
I will try to search more about it. Do you think I delete my issue here or only close?
Thank you for help!!

**Comment by sprankhub** [comment]
Glad you solved it. We can simply close the issue.
