### ISSUE TITLE
re-enable product and remove 301 redirect

### ISSUE THREAD

**Issue by skick5588** [adampmoss/CreareSEO#125]
I am using the feature for disabled product, discontinued - 301 redirect to category, however on occasion i need to re-enable a product and remove the redirect, is this an option? 
(without having to manually edit the htaccess to remove the redirect)
Magento ver. 1.9.1.0
CreareSEO version 1.5

**Comment by sprankhub** [comment]
Mind that the redirect is not implemented in the `.htaccess`, it is implemented as an observer: https://github.com/adampmoss/CreareSEO/blob/bdaf4b6e53a043a5b8366bc3995d74795a444848/app/code/community/Creare/CreareSeoCore/Model/Observer.php#L80-L115

It handles the event `controller_action_noroute`. Hence, if you simply enable the product again, the redirect will not be executed any more. If it is still executed, check the usual stuff (reindex and clear cache).
