### ISSUE TITLE
HTML Sitemap - CMS Page URLs are relative

### ISSUE THREAD

**Issue by adamj88** [adampmoss/CreareSEO#127]
The CMS page URLs in the HTML sitemap are relative to the current URL, see: https://github.com/adampmoss/CreareSEO/blob/master/app/design/frontend/base/default/template/creareseo/sitemap/sitemap.phtml#L8

This causes problems when the HTML sitemap is loaded as the following URL: https://www.baseurl.com/sitemap/

As these links point to https://www.baseurl.com/sitemap/cms-identifier

**Comment by sprankhub** [comment]
I could not reproduce the issue, but relative URLs suck, so it is a good idea to use the full URL anyway. I took the code from `Mage_Cms_Helper_Page::getPageUrl`. I copied the relevant part, so that the CMS page is not loaded again.
