### ISSUE TITLE
Database error on frontend product page

### ISSUE THREAD

**Issue by bquindo** [adampmoss/CreareSEO#129]
Hello,
when I try to create a new product associated with no category I receive the error attached 
[error.txt](https://github.com/adampmoss/CreareSEO/files/1348349/error.txt)
when visiting the product page url in front end after saved it. Instead, if I associate it to a category and save it and then visite the url in front end, the product is showed correctly without error.
How can I edit the "indicted" file  in order to not show error if a product is not associated with a category?

**Comment by sprankhub** [comment]
I could reproduce this issue when using `[first_category]` or `[categories]` in the default product title. Will fix this in a minute.

**Comment by bquindo** [comment]
I'm sorry, I don't undertand what am I supposed to do to solve the issue. What do I have to change?

**Comment by sprankhub** [comment]
Please download the [latest version](https://github.com/adampmoss/CreareSEO/archive/master.zip) and update the extension in your shop. You should not get the error any more.

**Comment by bquindo** [comment]
Thank you! It works!
