### ISSUE TITLE
Fatal Error when Make "alt" tags madatory is enabled

### ISSUE THREAD

**Issue by hejhog** [adampmoss/CreareSEO#134]
Set Make "alt" tags mandatory on product gallery images? => Yes

Try to edit a product.

Fatal error: Undefined class constant 'XML_NODE_PRODUCT_MAX_DIMENSION' in /app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml on line 85

**Comment by sprankhub** [comment]
Duplicate of https://github.com/adampmoss/CreareSEO/issues/93
