### ISSUE TITLE
Product Schema - No Condition

### ISSUE THREAD

**Issue by catgirl36** [adampmoss/CreareSEO#141]
Hello,

We have been altered by google that under our product schema, the condition is not available.

It is under the facebook schema on the extension, could this be added under product schema too?

We have version 1.4.0, so maybe this has been changed since then?

**Comment by sprankhub** [comment]
This is [part of the current product schema](https://github.com/adampmoss/CreareSEO/blob/c0bed40ad7629248c9275ac189219e22f5c4924e/app/design/frontend/base/default/template/creareseo/product/schema.phtml#L55), so that an update should solve your issue.
