### ISSUE TITLE
Upgrade M2

### ISSUE THREAD

**Issue by venture-travels** [adampmoss/CreareSEO#156]
Is there any upgrade to Magento 2.3?
Since  more and more signals are pointing to the end of life of Magento 1, it is clear the future in not in M 1. 
CreareSEO is so very very helpfull, but can it be used in M 2? I upgraded to M2 and i am missing CreareSeo so much. Is there any alternative now?
Thank you so much
Piet

**Comment by sprankhub** [comment]
I do not think that this is currently planned. You could check the following alternatives:

- [free, does not seem to be supported any more) [MaxServ_YoastSeo](https://github.com/Yoast/Yoast-SEO-for-Magento2)
- [free] [Staempfli_Seo](https://github.com/staempfli/magento2-module-seo)
- [free] [Brandung_Seo](https://github.com/brandung/magento2-module-seo)
- [paid, massive feature set] [MageWorx_Seo](https://www.mageworx.com/magento-2-seo-extension.html)

**Comment by venture-travels** [comment]
Thank you for the info.
Pity there is no M2 upgrade.
There is FoxSeo here on github ( https://github.com/adampmoss/foxseo2 ) , which was meant to be the upgrade. However, the code seems to have bugs and does not work on my M2.3.
Maybe small bugs (i think it is like that) but beyond my knowledge to solve. It can be installeled in M2.3, but blocks the website on frontend. All features on backend seem to be okay.
