### ISSUE TITLE
Feature request: [first_category_name], [category_names] tag in meta fields

### ISSUE THREAD

**Issue by singalen** [adampmoss/CreareSEO#33]
I know that a product can have a multiple categories.
So it in general doesn't make sense to ask about "product's category". From a data model point of view.
But in real life, in a lot of cases product only has a single category.

I'm asking about the possibility to use product's first (in whatever order) category name in meta tags, like `[first_category_name]`, or `[category_names]` - all names concatenated.

Thanks!

**Comment by adampmoss** [comment]
This is a feature that we have earmarked for a future update.

**Comment by teknology** [comment]
+1 for this. It will help with url structure and Meta information match.

**Comment by Phizik-PRO** [comment]
+100500 for this

**Comment by adampmoss** [comment]
Had a quick go an seems to work well: https://github.com/adampmoss/CreareSEO/pull/83/files

Penciled for next release if you guys happy?

**Comment by adampmoss** [comment]
Added in release 1.5: https://github.com/adampmoss/CreareSEO/releases/tag/1.5
