### ISSUE TITLE
Update logo schema template - logo url is odd...

### ISSUE THREAD

**Issue by sam327** [adampmoss/CreareSEO#42]
I'm getting a weird url for my logo when I enable the Logo Schema. On the page, it's showing up as
```
"logo": "http://mysite.com/skin/frontend/base/default/http://mysite.com/media/logo/logo.png"
```

In /template/creareseo/logo/schema.phtml

I think this line:
```
"logo": "<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')) ?>"
```

May need to be this:
```
"logo": "<?php echo Mage::getStoreConfig('design/header/logo_src') ?>"
```

**Comment by adampmoss** [comment]
It depends on how you enter your logo URL in the config. Most sites I've seen will use a relative path like "images/logo.jpg" rather than a full URL.
