### ISSUE TITLE
Magento 2.0 support

### ISSUE THREAD

**Issue by yasinkocak** [adampmoss/CreareSEO#43]
Will be great if this extension support Magento 2.0

**Comment by bavington** [comment]
Magento 2.0 support has been completed by @adampmoss, and will be debuting on the new Magento Connect as it was selected to be part of the launch. It will also be boasting some great new features too!

**Comment by yasinkocak** [comment]
That's great!! Any idea when will be launch?

**Comment by yasinkocak** [comment]
Is there any updates of Magento 2 support?

**Comment by adampmoss** [comment]
@yasinkocak there is a module available for Magento 2 which was going to be added to Magento Marketplace but those plans have now been cancelled - I'll make it available on GitHub shortly

**Comment by adampmoss** [comment]
Magento 2 version is here: https://github.com/adampmoss/foxseo2

It's not 100% yet so don't use it in production until it's fully tested
