### ISSUE TITLE
Remove meta_keywords

### ISSUE THREAD

**Issue by yasinkocak** [adampmoss/CreareSEO#47]
Options to remove meta keywords - AFAIK no search engines use them for search ranking at all. There's no need for them to be included.

**Comment by adampmoss** [comment]
This is already a feature of the extension in System > Config > CreareSEO > General Settings

<img width="651" alt="screen shot 2016-10-27 at 21 58 46" src="https://cloud.githubusercontent.com/assets/4948435/19785246/9bb52092-9c90-11e6-836c-bef1b070c618.png">
