### ISSUE TITLE
Aggregate Rating defaults to 1 if empty... 

### ISSUE THREAD

**Issue by sam327** [adampmoss/CreareSEO#49]
Default to a rating of 1 seems like shooting yourself in the foot. I had items where people left reviews but didn't leave a rating, so I ended up with products that were showing a 1 star rating, even though the reviews were glowing. 

Starting around line 50 in `/app/design/frontend/<theme-package>/<theme-template>/template/creareseo/product/schema.phtml`

````
],
"aggregateRating": {
    "@type": "AggregateRating",
    <?php $ratingValue = round($_totalAverageRating/$this->getReviewsCount(), 1) ?>
        <?php if ($ratingValue > 0) : ?>
    "ratingValue": "<?php echo $ratingValue ?>",
    <?php else: ?>
    "ratingValue": "1",
    <?php endif ?>
    "reviewCount": "<?php echo $this->getReviewsCount() ?>"
  }
````
Should wrap the aggregate rating block in an if check. If has ratings & rating is equal to or higher than the minimum, then show the block. Something more like this:

````
]
<?php $ratingValue = round($_totalAverageRating/$this->getReviewsCount(), 1) ?>
<?php if ($ratingValue >= 1) : ?>,
"aggregateRating": {
    "@type": "AggregateRating",    
    "ratingValue": "<?php echo $ratingValue ?>",
    "reviewCount": "<?php echo $this->getReviewsCount() ?>"
  }
 <?php endif; ?>
````

**Comment by adampmoss** [comment]
Good shout, this will be in the next release
