### ISSUE TITLE
NOINDEX for Checkout and Account Pages

### ISSUE THREAD

**Issue by sprankhub** [adampmoss/CreareSEO#51]
Similar to the other NOINDEX options, I think there should also be options to activate noindex for the checkout and the account pages. Right? I am happy to provide a PR if you would like to include this feature.

**Comment by adampmoss** [comment]
Surely the checkout page cannot get indexed as Google bot would find an empty cart?

Cart page and account page is a good shout though. If you're still up for it I'll happily review a PR.

**Comment by yasinkocak** [comment]
Disable this at robots.txt
