### ISSUE TITLE
The review has no reviewed item specified.

### ISSUE THREAD

**Issue by smartteck** [adampmoss/CreareSEO#56]
i have installed this extension. all seem to be fine but for the product i have one review it is giving one error in [google testing tool](https://developers.google.com/structured-data/testing-tool?url=https%253A%252F%252Fwww.smartteck.co.uk%252Fwestern-digital-red-4tb-6gbps.html)
i have checked all the settings and found no issue any where.
any help?

**Comment by sasoriza** [comment]
I am seeing the same error. Please advice how to fix this, adding

    "itemReviewed": {
      "@type": "Product",
      "image": "<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage()) ?>",
      "name": "<?php echo $this->cleanString($_product->getName()) ?>"
    },

to product/schema.phtml isn't working.

**Comment by adampmoss** [comment]
@sasoriza @smartteck thanks for the feedback - the whole schema element needs updating as it was written quit e along time ago and has been unattended for a while.
