### ISSUE TITLE
Unable to view Defualt SEO Check

### ISSUE THREAD

**Issue by wood1e** [adampmoss/CreareSEO#65]
Hi, 

I have installed the module on Mag V1.9.2.4 but when I click on 'Default SEO Check' I get just a blank screen...along with magentos admin menu/header.

Has anyone experience of this? Could it be a file persmission issue?  Or something else?

Any help would be most appreciated.

**Comment by adampmoss** [comment]
Hello @wood1e are you still experiencing this problem?
