### ISSUE TITLE
Add schema.org Product Brand

### ISSUE THREAD

**Issue by sprankhub** [adampmoss/CreareSEO#67]
The `brand` attribute should be added to the product schema. If one simply uses the standard `manufacturer` attribute, the following addition to `app/design/frontend/base/default/template/creareseo/product/schema.phtml` should be enough:

    "brand": "<?php echo $this->cleanString($_product->getAttributeText('manufacturer')) ?>",

You may want to add a configuration for the used attribute though.

**Comment by adampmoss** [comment]
Coming up in next release
