### ISSUE TITLE
Edit product

### ISSUE THREAD

**Issue by informundo** [adampmoss/CreareSEO#71]
When I edit one product don´t show the atributes discontinued and discontinued_product (see edit_product.png). When add  a product, if it appears (see add_product.png).
In this case, in the dropdown,the last option are ¿84?.
![add_product](https://cloud.githubusercontent.com/assets/8274587/16546507/1859b17a-414d-11e6-9db6-7ea29a8dddfc.png)
![edit_product](https://cloud.githubusercontent.com/assets/8274587/16546508/1c45ab5e-414d-11e6-8757-265233edfa0c.png).
Thanks

**Comment by adampmoss** [comment]
I'm unable to replicate this problem, i expect there's a conflict with your Magento installation. I'll close this issue, but feel free to reopen if you want further support
