### ISSUE TITLE
HTTPS and HTTP CMS page canonicals

### ISSUE THREAD

**Issue by JamesFX2** [adampmoss/CreareSEO#72]
Hey

CreareSEO/app/code/community/Creare/CreareSeoCore/Block/Page/Html/Head/Cmscanonical.php

Your plugin is spitting out different canonical tags on mixed HTTPs/HTTP sites.

Your plugin is outputting a HTTPs canonical tag on CMS pages if the URL is HTTPs and a HTTP canonical tag if the URL is HTTP. 

So https://example.com/delivery-info/ and http://example.com/delivery-info/ - you would want both to point to either the HTTP or HTTPs version, depending on which is setup in Magento config. This kind of defeats part of the point of canonical tags - if the "same" URL has 2 different signals.

I think you'll need to have it pull in the **secure base link URL** and **unsecure base link URL** instead of just using getHost on the URL.

To configure Magento sites, you tend to set both the unsecure base URL and secure base URL to the same thing - so both as the HTTP or HTTPs version of the site. I'm not sure this is intended but it ensures that the sitemap/internal links/canonical tags on categories and products are the preferred version. So if you switch to HTTPs fully, you may set both the unsecure and secure URL to HTTPs so that the sitemap spits out the right version and other things work properly.

**Comment by adampmoss** [comment]
Was this what you had in mind? https://github.com/adampmoss/CreareSEO/pull/82/files

**Comment by adampmoss** [comment]
Updated in 1.5: https://github.com/adampmoss/CreareSEO/releases/tag/1.5
