### ISSUE TITLE
Sitemap Disable

### ISSUE THREAD

**Issue by heartlandbr** [adampmoss/CreareSEO#74]
I would like to use a different extension for a HTML SiteMap and XML SiteMap. Is there a way to just disable the HTML SiteMap and XML SiteMap of CreareSEO?

**Comment by adampmoss** [comment]
The only way to fully disable the sitemap and get back the /sitemap URL is to disable the module via XML in **app/etc/modules/Creare_CreareSeoSitemap.xml**:

```
<config>
    <modules>
        <Creare_CreareSeoSitemap>
            <active>false</active>
            <codePool>community</codePool>
        </Creare_CreareSeoSitemap>
    </modules>
</config>
```
