### ISSUE TITLE
SUPEE 8788 Problem

### ISSUE THREAD

**Issue by jorgb90** [adampmoss/CreareSEO#79]
Productpages are not working anymore when Magento 1.9.2.4 is patched with SUPEE-8788. You will get a Too many redirects error. This only happens when you have more then one tag after the url so for example https://www.domain.com/producturl?utm_source=source&utm_medium=medium&utm_campaign=campaign

**Comment by GKnd** [comment]
I am also facing this problem for all my product pages when Enable Canonical Product Redirecting is set to Yes

**Comment by lfolco** [comment]
This is also occurring on an EE store (v1.13.1.0).

**Comment by lfolco** [comment]
I had to disable the extension entirely; turning off the canonical product redirecting did not work.

**Comment by sprankhub** [comment]
I can confirm this very critical (!) issue.

**Comment by webwarecare** [comment]
Can confirm lfolco's commit above resolved the issue on a clients site.

**Comment by sprankhub** [comment]
This can be closed since a bugfix version has been released.
