### ISSUE TITLE
Magento 1.9.3.0 - Product.Gallery is broken in adminhtml

### ISSUE THREAD

**Issue by JulienPradet** [adampmoss/CreareSEO#80]
Since the upgrade, the module has broken the admin for product images.

In the file  `CreareSEO/app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml`, when declaring the `new Product.Gallery`, the second parameter is to be removed.

**Comment by savla-jigs** [comment]
I am also facing the same issue on Magento 1.9.1.0 with condition 

> Make "alt" tags mandatory on product gallery images? set as YES

**Comment by adampmoss** [comment]
This has been fixed in release 1.4.2.1
