### ISSUE TITLE
Product view page blank

### ISSUE THREAD

**Issue by darekkosyl** [adampmoss/CreareSEO#84]
We've just put your 1.4.2.1 on our magento 1.9.2.4 site and our product view page is just blank. Had to disable.

**Comment by Quazz** [comment]
https://github.com/adampmoss/CreareSEO/commit/1f50a63ae701df965251ae8fe1c90299c68780ad

This is the culprit. 

If you don't have manufacturer data filled in, it will throw an error about a null value and the php process will crash.

**Comment by kryss05** [comment]
I confirm same problem, blank page product in front and admin page.

**Comment by adampmoss** [comment]
This is fixed recently so please upgrade: https://github.com/adampmoss/CreareSEO/blob/master/app/design/frontend/base/default/template/creareseo/product/schema.phtml
