### ISSUE TITLE
Certain category pages set robots to noindex

### ISSUE THREAD

**Issue by casperNL** [adampmoss/CreareSEO#89]
Hi Adam,

I have a strange Issue, some of my category pages are set to noindex, even when my custom page layout is set to: 

```
<reference name="root">
    <action method="setTemplate">
        <template>page/1column.phtml</template>
    </action>
</reference>
<reference name="head">
   <action method="setRobots"><value>INDEX,FOLLOW</value></action>
</reference>
```

When I save the category in magento the robots are again set to index, follow.

I asked my webhost for this strange behavior and they mentioned that creare seo plugin has the ability to change the robots of a category page.

Is CreareSEO causing this, or should I look somewhere else? And if CreareSEO is causing this, is there a way to disable this behavior for category pages (I saw no option for this in the plugin options).

BTW, youre plugin is awesome!
MY

**Comment by adampmoss** [comment]
Hello, I'll take a look at this for you now.

**Comment by adampmoss** [comment]
@casperNL there's an observer that runs a script every time the category page is loaded.

The script will check to see if there's a question mark (querystring) in the URL, and if so it will set the robots to nofollow. Do your category URLs contain any question marks?

I'm about to refactor this code so I'll double-check things as I go.

**Comment by casperNL** [comment]
Hi Adam,

No there is no questionmark in the category url.

Op 14 nov. 2016 10:01 p.m. schreef "Adam Moss" <notifications@github.com>:

**Comment by adampmoss** [comment]
Could you try commenting out lines 9 to 19 of this file and let me know if it fixes it?

https://github.com/adampmoss/CreareSEO/blob/master/app/code/community/Creare/CreareSeoCore/Model/Observer.php#L9

**Comment by casperNL** [comment]
Hi Adam,
Thx for the fast Response, will this change Have consequenses for the
noindex of filtered category  pages?

Op 14 nov. 2016 10:05 p.m. schreef "Adam Moss" <notifications@github.com>:

**Comment by adampmoss** [comment]
Yes, I suggest you do it in a test environment first - we need to know first whether it's causing the problem. If so, we then need to understand why it's bypassing the if conditional without a question mark.

**Comment by casperNL** [comment]
Hi Adam, im testing in our staging environment atm, is this the jobs name?
creare_creareseocore . thanks.

2016-11-15 9:49 GMT+01:00 Adam Moss <notifications@github.com>:

**Comment by adampmoss** [comment]
Hi @casperNL, what do you mean by the 'job'?

**Comment by casperNL** [comment]
Hi Adam, I mean scheduled tasks by that, sounds fermilliar? Sorry im not a
programmer :).

BTW, I did run creare_creareseocore on our staging environment but no
noindex is added to the header for the problematic page on our live
environment.

Met vriendelijke groet,

Casper Konings

*06-33982075*

*INTERNET MARKETING* | Website <http://www.myecommerce.nl/> | Blog
<http://www.myecommerce.nl/blog/> | Google+
<https://plus.google.com/110724719745648486407/posts> | LinkedIn
<https://www.linkedin.com/pub/casper-konings/1b/b76/643> | Google
<https://www.google.com/partners/?hl=nl#i_profile;idtf=115916268745649614228;>
certificering
<https://www.google.com/partners/?hl=nl#i_profile;idtf=115916268745649614228;>

*Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit
bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de
afzender te melden. King e-Commerce staat door de elektronische verzending
van dit bericht niet in voor de juiste en volledige overbrenging van de
inhoud, noch voor tijdige ontvangst daarvan.*

2017-02-07 14:30 GMT+01:00 Adam Moss <notifications@github.com>:

**Comment by casperNL** [comment]
Hi adam, 

> 
> 
> @casperNL there's an observer that runs a script every time the category page is loaded.
> 
> The script will check to see if there's a question mark (querystring) in the URL, and if so it will set the robots to nofollow. Do your category URLs contain any question marks?
> 
> I'm about to refactor this code so I'll double-check things as I go.

**Comment by casperNL** [comment]
> @casperNL there's an observer that runs a script every time the category page is loaded.
> 
> The script will check to see if there's a question mark (querystring) in the URL, and if so it will set the robots to nofollow. Do your category URLs contain any question marks?

Hi, how to trigger this 

> @casperNL there's an observer that runs a script every time the category page is loaded.

How to trigger this observer?
