### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by Morgy93** [adampmoss/CreareSEO#97]
Got this error after clearing the cache:

`a:5:{i:0;s:658:"Error in file: "app/code/community/Creare/CreareSeoCore/sql/creareseo_setup/mysql4-upgrade-1.0.0-1.0.1.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-creareseo_discontinued_product' for key 'UNQ_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE', query was: INSERT INTO `eav_attribute` (`entity_type_id`, `attribute_code`, `backend_model`, `backend_type`, `backend_table`, `frontend_model`, `frontend_input`, `frontend_label`, `frontend_class`, `source_model`, `is_required`, `is_user_defined`, `default_value`, `is_unique`, `note`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";i:1;s:1117:"#0 app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 app/code/core/Mage/Core/Model/Resource/Setup.php(422): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '1.0.0', '1.5')
#2 app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('1.5')
#3 app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 app/Mage.php(692): Mage_Core_Model_App->run(Array)
#7 index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:25:"/index.php/admin/cache/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}`

But after hitting F5, the page loaded and the extension seems to work.

Probably it's a won't fix? Dunno..

**Comment by adampmoss** [comment]
I have experienced this happening with other modules in the past, I think it's a momentary cache issue -  from a technical POV I'm not entirely sure why it happens but I don't think it is specifically a problem with the extension.
