### ISSUE TITLE
Backend White Screen -Manage Products-New Product- Font Still Showing Bug/Glitch

### ISSUE THREAD

**Issue by ljseals** [adampmoss/CreareSEO#98]
When you add new product get white screen with black font no styling. Restored backup from installation problem is not there. Using version 1.9.2.4 and downloaded that latest version of CreareSEO off github. Thanks for the free extension! God bless you!
``
Fatal error: Uncaught Error: Undefined class constant 'XML_NODE_PRODUCT_MAX_DIMENSION' in /home/nginx/domains/domain/public/app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml:85 Stack trace: #0 /home/nginx/domains/domain/public/app/code/core/Mage/Core/Block/Template.php(241): include() #1 /home/nginx/domains/domain/public/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...') #2 /home/nginx/domains/domain/public/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView() #3 /home/nginx/domains/domain/public/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml() #4 /home/nginx/domains/domain/public/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml() #5 /home/nginx/domains/domain/public/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Gallery.php(59): in /home/nginx/domains/domain/public/app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml on line 85``

**Comment by ljseals** [comment]
I was mistaken and the version 1.5.1 fixes this issues. When downloading from the main page you will get 1.5.0 version. God bless you!

**Comment by ljseals** [comment]
Well, I have narrowed the issue down to one specific problem. However, I was using version 1.5.0 now I am using 1.5.1 and the problem arises when I apply the **Make "alt" tags mandatory on product gallery images?

I currently do not have any products or product images on my website. Regards
![screen](https://cloud.githubusercontent.com/assets/25220839/22106439/62d72e2c-de0e-11e6-882e-fe2bd616352d.jpg)

**Comment by ljseals** [comment]
I just upgraded Magento to the lastest version but will close this ticket as it has not been answered. God bless you!

**Comment by Jeeva-Rathinam** [comment]
Is your issue solved?
